environment:
    DEPLOY_PROVIDER: bintray
    BINTRAY_ACCOUNT: larskanis
    BINTRAY_REPOSITORY: rubyinstaller2-packages
    PACMAN_REPOSITORY_NAME: ci.mingw
    BUILD_URL: https://ci.appveyor.com/project/$(APPVEYOR_ACCOUNT_NAME)/$(APPVEYOR_PROJECT_NAME)/build/$(APPVEYOR_BUILD_VERSION)

build_script:
    - C:\msys64\usr\bin\pacman --noconfirm --sync --refresh --refresh --sysupgrade --sysupgrade
    - C:\msys64\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/ci-build.sh"

artifacts:
    - path: artifacts\*

deploy:
    - provider: BinTray
      username: $(BINTRAY_ACCOUNT)
      subject: $(BINTRAY_ACCOUNT)
      repo: $(BINTRAY_REPOSITORY)
      package: $(PACMAN_REPOSITORY_NAME)
      version: latest
      publish: true
      override: true
      api_key:
          secure: yaAnKXWjX6uB9WwCZ4ZQm/R0bCvyribyGYEoTu/kw+F6v8CgJ26n8+u9C6cnuBIN
