init:
  - echo %PATH%
  # We use a clean PATH to avoid interferences with the hundreds of installed programs.
  - set PATH=c:/Ruby24-x64/bin;c:/Program Files/Git/cmd;c:/Windows/system32;c:/Windows/System32/WindowsPowerShell/v1.0
  # Remove troublesome files from Windows system directory
  - dir c:\windows\system32\l*.dll
  - del c:\windows\system32\libcrypto-1_1-x64.dll c:\windows\system32\libssl-1_1-x64.dll
  # Since system32 is a per-platform-directory, we need to execute the commands through a 32 bit cmd to remove the x86 versions
  - c:\windows\syswow64\cmd.exe /c "dir c:\windows\system32\l*.dll"
  - c:\windows\syswow64\cmd.exe /c "del c:\windows\system32\libcrypto-1_1.dll c:\windows\system32\libssl-1_1.dll"

environment:
    DEPLOY_PROVIDER: bintray
    BINTRAY_ACCOUNT: larskanis
    BINTRAY_REPOSITORY: rubyinstaller2-packages
    BINTRAY_VERSION: latest
    PACMAN_REPOSITORY_NAME: ci.ri2
    BUILD_URL: https://ci.appveyor.com/project/$(APPVEYOR_ACCOUNT_NAME)/$(APPVEYOR_PROJECT_NAME)/build/$(APPVEYOR_BUILD_VERSION)
    GPGPASSWD:
        secure: /DELcKSZC+R4HdXgsqR1RtC+IrDZ3Xut/vzV/KgepE3M8OsjJtmWutN0+Jvc2Iv2
    BINTRAY_API_KEY:
        secure: yaAnKXWjX6uB9WwCZ4ZQm/R0bCvyribyGYEoTu/kw+F6v8CgJ26n8+u9C6cnuBIN

build_script:
    # Avoid repo.msys2.org since it's down currently
    - c:\msys64\usr\bin\bash -lc "sed -e \"/repo.msys2.org/ s/Server/#Server/\" -i /etc/pacman.d/mirrorlist.*"
    - c:\msys64\usr\bin\bash -lc "cat /etc/pacman.d/mirrorlist.*"
    # Update keyring according to https://www.msys2.org/news/#2020-06-29-new-packagers
    - C:\msys64\usr\bin\curl -O http://mirror.yandex.ru/mirrors/msys2/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
    - C:\msys64\usr\bin\curl -O http://mirror.yandex.ru/mirrors/msys2/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig
    - ridk exec bash -c "pacman-key --verify msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
    - ridk exec bash -c "pacman -U --noconfirm --config <(echo) msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
    # Remove gcc-ada and gcc-objc, since they are no longer supported by msys2 and therefore cause a dependency issue
    - C:\msys64\usr\bin\pacman --noconfirm --remove mingw-w64-i686-gcc-ada mingw-w64-i686-gcc-objc mingw-w64-x86_64-gcc-ada mingw-w64-x86_64-gcc-objc
    - C:\msys64\usr\bin\pacman --noconfirm --ask 20 --sync --refresh --refresh --sysupgrade --sysupgrade
    # Kill all running msys2 binaries to avoid error "size of shared memory region changed".
    # See https://github.com/msys2/MSYS2-packages/issues/258
    - powershell -Command "Get-Process | Where-Object {$_.path -like 'C:\msys64*'} | Stop-Process"
    - C:\msys64\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/ci-build.sh"

artifacts:
    - path: artifacts\*

deploy:
    - provider: BinTray
      username: $(BINTRAY_ACCOUNT)
      subject: $(BINTRAY_ACCOUNT)
      repo: $(BINTRAY_REPOSITORY)
      package: $(PACMAN_REPOSITORY_NAME)
      version: latest
      publish: true
      override: true
      api_key: $(BINTRAY_API_KEY)
